version: '3'
services:
  nginx:
    build: docker/nginx
    tty: true
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    ports:
      - "8888:80"
  php:
    build: docker/php
    tty: true
    volumes:
      - ./app:/app
