Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.network "private_network", ip: "192.168.51.10"

    config.vm.synced_folder ".", "/vagrant", type: "virtualbox", :mount_options => ['dmode=777']

   config.vm.provision "shell", path: './install.sh'
end

